title: Site officiel de de nos formations en IA.
description: Calepins d'auto-apprentissage en Science des Données & Intelligence Artificielle. Toutes nos formations sont ici.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
